In [10]:
#Linear regression libs
import numpy as np
from sklearn.linear_model import LinearRegression


In [11]:
#data: predictor x and regressor y,
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
print(x) #one column and as many rows as necessary
y = np.array([5, 20, 14, 32, 22, 38])
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [13]:
# regression application
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#whether the model works satisfactorily and interpret it.
#You can obtain the coefficient of determination (𝑅²)
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

#𝑏₀ and 𝑏₁
print('intercept:', model.intercept_)
print('slope:', model.coef_)

coefficient of determination: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]


In [16]:
#predictions with either existing or new data.
y_pred = model.predict(x) # y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [19]:
#multiple linear regression

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
print(x)
print(y)
model = LinearRegression().fit(x, y)

r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('slope:', model.coef_)


y_pred = model.predict(x) # same with below
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]
[ 4  5 20 14 32 22 38 43]
coefficient of determination: 0.8615939258756776
intercept: 5.5225792751981935
slope: [0.44706965 0.25502548]


In [21]:
#polynomial regression
from sklearn.preprocessing import PolynomialFeatures

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

# need to include 𝑥² (and perhaps other terms) as additional features 
# transform the input array x to contain the additional column(s)
# with the values of 𝑥² (and eventually more features).

x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)
print(x_)

model = LinearRegression().fit(x_, y)

r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('coefficients:', model.coef_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]
coefficient of determination: 0.8908516262498564
intercept: 21.372321428571453
coefficients: [-1.32357143  0.02839286]
